"""add user and userid

Revision ID: 0c8ffc348f78
Revises: 
Create Date: 2020-02-27 21:44:54.510112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8ffc348f78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_id',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_table',
    sa.Column('user_index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=30), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_age', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_id.id'], ),
    sa.PrimaryKeyConstraint('user_index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_table')
    op.drop_table('user_id')
    # ### end Alembic commands ###
