"""more2more2

Revision ID: 85f848900bdc
Revises: 88a968ed5317
Create Date: 2020-02-27 23:17:21.862071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f848900bdc'
down_revision = '88a968ed5317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('cno', sa.String(length=20), nullable=True))
    op.add_column('teacher', sa.Column('tno', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'tno')
    op.drop_column('classes', 'cno')
    # ### end Alembic commands ###
