"""more2more

Revision ID: 88a968ed5317
Revises: b1afa8214f20
Create Date: 2020-02-27 23:02:00.462541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a968ed5317'
down_revision = 'b1afa8214f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_classes',
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('classes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classes_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_classes')
    op.drop_table('teacher')
    op.drop_table('classes')
    # ### end Alembic commands ###
