"""one2more

Revision ID: b1afa8214f20
Revises: 0c8ffc348f78
Create Date: 2020-02-27 21:49:37.823401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1afa8214f20'
down_revision = '0c8ffc348f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('one_table',
    sa.Column('one_index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('one_name', sa.String(length=30), nullable=True),
    sa.Column('one_id', sa.Integer(), nullable=True),
    sa.Column('one_age', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['one_id'], ['user_id.id'], ),
    sa.PrimaryKeyConstraint('one_index')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_name', sa.String(length=30), nullable=True),
    sa.Column('one_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['one_id'], ['one_table.one_index'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    op.drop_table('one_table')
    # ### end Alembic commands ###
